### ISSUE TITLE
how to start tomcat?

### ISSUE THREAD

**Issue by sunrong** [ralscha/embeddedtc#3]
I run JUnit Test of  startServer(the name in your source), It prints

Oct 12, 2015 3:50:44 pm org.apache.coyote.AbstractProtocol init
Info: Initializing ProtocolHandler ["http-nio-9998"]
Oct 12, 2015 3:50:44 pm org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
Info: Using a shared selector for servlet write/read
Oct 12, 2015 3:50:45 pm org.apache.jasper.servlet.TldScanner scanJars
Info: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
Oct 12, 2015 3:50:45 pm org.apache.coyote.AbstractProtocol start
Info: Starting ProtocolHandler ["http-nio-9998"

It seems everything is OK except   I cannot open the page in browser.

Could you please say more about how  to use it?

**Comment by ralscha** [comment]
How do you open the page?

**Comment by sunrong** [comment]
I use url http://localhost:9998/index.html. I create a dir whose name is webapp in embeddedtc\src\main and put a index.html into it.

**Comment by sunrong** [comment]
My problem is after I run startServer,  I run "netstat -ano|findstr 9998" and there is no ouput there which seems the server is down without listening the port 9998.

**Comment by ralscha** [comment]
The server should listen on the port when you see this line
```Info: Starting ProtocolHandler ["http-nio-9998"```

Don't really know what the problem could be.
