### ISSUE TITLE
how to unzip WAR in ContextDirectory automatically when tomcat starts?

### ISSUE THREAD

**Issue by sunrong** [ralscha/embeddedtc#4]
I create a class in my project, create an instance of EmbeddedTomcat, start the server with startAndWait().I put a war in ContextDirectory before. server does not unzip the war.so I cannot browse its page.
how to make  a unzip war during starting server?
I can browse mywebapp in ContextDirectory.

thanks in advanced.

**Comment by ralscha** [comment]
You could write code that unzips the war. 
Here is an example: http://www.mkyong.com/java/how-to-decompress-files-from-a-zip-file/
And after the unzip step you start the server

I always used this maven plugin https://github.com/ralscha/embeddedtc-maven-plugin 
This plugin creates an executable jar that bundles the tomcat server and the application into one package. No need to unpack a war.

But for newer applications I use [Spring Boot](http://projects.spring.io/spring-boot/). If you don't like Spring [Dropwizard](http://www.dropwizard.io/) is an alternative that does the same. They both bundle the webserver with the application and create an executable jar.
